CC = g++ -std=c++11
PARA = -g
INC = -I./ -I/usr/local/include
LINKDIR = -L/usr/local/lib
LINKFILE = -ljpeg
TARGET = fbsave
SRC = fbsave1.cpp

all:
	$(CC) $(PARA) $(INC) $(SRC) -o $(TARGET) $(LINKDIR) $(LINKFILE)

